version: '3.7'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - AUTORUN_ENABLED=false
        ports:
            - '${APP_PORT:-8080}:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - app_network
        container_name: app

networks:
    app_network:
        driver: bridge
